<div style="text-align:center;">
  <h1 size=10>
    <b>MLOps PROJECT</b><br>
    <b></b>
  </h1>
</div>

<h2 style="text-align:center;">
Master's in Data Science and Advanced Analytics - NOVA IMS (25/26)
</h2>

**Group ??**
- Bárbara Franco (20250388)
- Catarina Aboim (2025????)
- Catarina Mendinhas (20250422)
- Maria Miguel Fonseca (20250380)

**GitHub repository:**

<font color='#2f94d7' size=6>**TABLE OF CONTENTS**</font> <a class="anchor" id='toc'></a>

- [1. Project Overview](#1)
- [2. Set Up & Import Libraries](#2)
- [3. Load Data](#3)
- [4. Data Exploration](#4)

# <font color='#2f94d7' size=6>**1. Project Overview**</font> <a class="anchor" id="1"></a>

[Back to TOC](#toc)

# <font color='#2f94d7' size=6>**2. Set Up & Import Libraries**</font> <a class="anchor" id="2"></a>

[Back to TOC](#toc)

In [2]:
import pandas as pd

# <font color='#2f94d7' size=6>**3. Load Data**</font> <a class="anchor" id="3"></a>

[Back to TOC](#toc)

In [14]:
df_train = pd.read_csv('../data/portugal_listinigs.csv')

/var/folders/s9/nfpy2jls4ps2k_p8lpjz6_yr0000gn/T/ipykernel_8697/1761435925.py:1: DtypeWarning: Columns (9,10,12,13,14,15,16,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df_train = pd.read_csv('../data/portugal_listinigs.csv')

# <font color='#2f94d7' size=6>**4. Data Exploration**</font> <a class="anchor" id="4"></a>

[Back to TOC](#toc)

In [20]:
df_train.shape

(135536, 25)

In [15]:
df_train.head()

,Price,District,City,Town,Type,EnergyCertificate,GrossArea,TotalArea,Parking,HasParking,...,Elevator,ElectricCarsCharging,TotalRooms,NumberOfBedrooms,NumberOfWC,ConservationStatus,LivingArea,LotSize,BuiltArea,NumberOfBathrooms
0,780000.0,Vila Real,Valpaços,Carrazedo de Montenegro e Curros,Farm,NC,200.0,552450.0,0.0,False,...,False,NaN,NaN,NaN,NaN,NaN,120.0,NaN,NaN,0.0
1,223000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,NaN,81.0,1.0,True,...,True,NaN,2.0,NaN,NaN,NaN,81.0,NaN,NaN,2.0
2,228000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,NaN,108.0,1.0,True,...,True,NaN,2.0,NaN,NaN,NaN,108.0,NaN,NaN,2.0
3,250000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,NaN,114.0,1.0,True,...,True,NaN,2.0,NaN,NaN,NaN,114.0,NaN,NaN,0.0
4,250000.0,Faro,São Brás de Alportel,São Brás de Alportel,Apartment,A+,NaN,114.0,1.0,True,...,True,NaN,2.0,NaN,NaN,NaN,114.0,NaN,NaN,2.0

In [16]:
df_train.tail()

,Price,District,City,Town,Type,EnergyCertificate,GrossArea,TotalArea,Parking,HasParking,...,Elevator,ElectricCarsCharging,TotalRooms,NumberOfBedrooms,NumberOfWC,ConservationStatus,LivingArea,LotSize,BuiltArea,NumberOfBathrooms
135531,130000.0,Setúbal,Palmela,Palmela,Land,NC,NaN,1189.0,0.0,NaN,...,False,False,NaN,NaN,0.0,NaN,NaN,1189.0,NaN,0.0
135532,45000.0,Viana do Castelo,Ponte de Lima,Labruja,House,NC,NaN,374.0,1.0,NaN,...,False,False,NaN,0.0,0.0,NaN,374.0,4370.0,NaN,0.0
135533,349900.0,Vila Real,Valpaços,Valpaços e Sanfins,House,F,NaN,188.0,1.0,NaN,...,False,False,NaN,3.0,1.0,NaN,190.0,18240.0,238.0,3.0
135534,50000.0,Vila Real,Alijó,Castedo e Cotas,House,NC,NaN,69.0,1.0,NaN,...,False,False,NaN,2.0,1.0,NaN,84.0,NaN,84.5,2.0
135535,35000.0,Vila Real,Valpaços,Algeriz,Land,NC,NaN,100.0,0.0,NaN,...,False,False,NaN,NaN,0.0,NaN,NaN,100.0,NaN,0.0

In [13]:
df_train.columns

Index(['Price', 'District', 'City', 'Town', 'Type', 'EnergyCertificate',
       'GrossArea', 'TotalArea', 'Parking', 'HasParking', 'Floor',
       'ConstructionYear', 'EnergyEfficiencyLevel', 'PublishDate', 'Garage',
       'Elevator', 'ElectricCarsCharging', 'TotalRooms', 'NumberOfBedrooms',
       'NumberOfWC', 'ConservationStatus', 'LivingArea', 'LotSize',
       'BuiltArea', 'NumberOfBathrooms'],
      dtype='object')

In [10]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135536 entries, 0 to 135535
Data columns (total 25 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Price                  135236 non-null  float64
 1   District               135536 non-null  object
 2   City                   135536 non-null  object
 3   Town                   135534 non-null  object
 4   Type                   135520 non-null  object
 5   EnergyCertificate      135522 non-null  object
 6   GrossArea              27638 non-null   float64
 7   TotalArea              127153 non-null  float64
 8   Parking                135342 non-null  float64
 9   HasParking             68215 non-null   object
 10  Floor                  27929 non-null   object
 11  ConstructionYear       88021 non-null   float64
 12  EnergyEfficiencyLevel  67289 non-null   object
 13  PublishDate            29239 non-null   object
 14  Garage                 67289 non-null   object
 15  Elevator               135504 non-null  object
 16  ElectricCarsCharging   67289 non-null   object
 17  TotalRooms             73244 non-null   float64
 18  NumberOfBedrooms       47041 non-null   float64
 19  NumberOfWC             57256 non-null   float64
 20  ConservationStatus     19292 non-null   object
 21  LivingArea             104952 non-null  float64
 22  LotSize                39583 non-null   float64
 23  BuiltArea              26617 non-null   float64
 24  NumberOfBathrooms      128700 non-null  float64
dtypes: float64(12), object(13)
memory usage: 25.9+ MB

In [11]:
df_train.describe()

,Price,GrossArea,TotalArea,Parking,ConstructionYear,TotalRooms,NumberOfBedrooms,NumberOfWC,LivingArea,LotSize,BuiltArea,NumberOfBathrooms
count,1.352360e+05,2.763800e+04,1.271530e+05,135342.000000,88021.000000,73244.000000,47041.000000,57256.000000,1.049520e+05,3.958300e+04,2.661700e+04,128700.000000
mean,3.681374e+05,2.789733e+03,5.140780e+05,0.549667,1989.303825,3.229357,2.665823,0.430785,1.403037e+03,5.636939e+04,3.086621e+03,1.544025
std,3.804044e+06,1.153670e+05,1.722937e+08,0.839257,26.684309,10.516977,1.790474,1.016360,3.474597e+04,5.208474e+06,1.185137e+05,1.764637
min,1.000000e+00,-7.000000e+00,-7.196067e+06,0.000000,1900.000000,0.000000,0.000000,-15.000000,0.000000e+00,0.000000e+00,-1.000000e+00,-13.000000
25%,8.400000e+04,1.000000e+02,9.100000e+01,0.000000,1973.000000,2.000000,2.000000,0.000000,8.000000e+01,2.580000e+02,1.045700e+02,0.000000
50%,2.100000e+05,1.640000e+02,1.590000e+02,0.000000,1994.000000,3.000000,3.000000,0.000000,1.180000e+02,6.790000e+02,1.680000e+02,1.000000
75%,3.950000e+05,2.940000e+02,5.000000e+02,1.000000,2009.000000,4.000000,3.000000,1.000000,2.040000e+02,2.890000e+03,3.000000e+02,2.000000
max,1.380000e+09,1.275000e+07,6.142007e+10,3.000000,2025.000000,2751.000000,21.000000,59.000000,5.429000e+06,9.923010e+08,1.275000e+07,131.000000

In [19]:
df_train.duplicated().sum()

np.int64(8913)

In [25]:
print(df_train.isnull().sum())
print()
print(f"Total missing values: {df_train.isna().sum().sum()}")

Price                       300
District                      0
City                          0
Town                          2
Type                         16
EnergyCertificate            14
GrossArea                107898
TotalArea                  8383
Parking                     194
HasParking                67321
Floor                    107607
ConstructionYear          47515
EnergyEfficiencyLevel     68247
PublishDate              106297
Garage                    68247
Elevator                     32
ElectricCarsCharging      68247
TotalRooms                62292
NumberOfBedrooms          88495
NumberOfWC                78280
ConservationStatus       116244
LivingArea                30584
LotSize                   95953
BuiltArea                108919
NumberOfBathrooms          6836
dtype: int64

Total missing values: 1237923